// feather ignore all
// Documentation: https://glebtsereteli.github.io/GMRoomLoader/pages/api/roomLoader/assetTypeFiltering

#macro ROOMLOADER_FLAG_NONE 0
#macro ROOMLOADER_FLAG_INSTANCES 1
#macro ROOMLOADER_FLAG_TILEMAPS 2
#macro ROOMLOADER_FLAG_SPRITES 4
#macro ROOMLOADER_FLAG_SEQUENCES 8
#macro ROOMLOADER_FLAG_PARTICLES 16
#macro ROOMLOADER_FLAG_TEXTS 32
#macro ROOMLOADER_FLAG_BACKGROUNDS 64
#macro ROOMLOADER_FLAG_EFFECTS 128

#macro ROOMLOADER_FLAG_CORE (ROOMLOADER_FLAG_INSTANCES | ROOMLOADER_FLAG_SPRITES | ROOMLOADER_FLAG_TILEMAPS)
#macro ROOMLOADER_FLAG_EXTENDED (ROOMLOADER_FLAG_SEQUENCES | ROOMLOADER_FLAG_PARTICLES | ROOMLOADER_FLAG_TEXTS | ROOMLOADER_FLAG_BACKGROUNDS | ROOMLOADER_FLAG_EFFECTS)
#macro ROOMLOADER_FLAG_ALL (ROOMLOADER_FLAG_CORE | ROOMLOADER_FLAG_EXTENDED)
