// feather ignore all
// Documentation: https://glebtsereteli.github.io/GMRoomLoader/pages/api/roomLoader/assetTypeFiltering

enum ROOMLOADER_FLAG {
	NONE = 0,
	INSTANCES = 1,
	TILEMAPS = 2,
	SPRITES = 4,
	SEQUENCES = 8,
	PARTICLES = 16,
	TEXTS = 32,
	BACKGROUNDS = 64,
	EFFECTS = 128,
	
	CORE = ROOMLOADER_FLAG.INSTANCES | ROOMLOADER_FLAG.SPRITES | ROOMLOADER_FLAG.TILEMAPS,
	EXTENDED = ROOMLOADER_FLAG.SEQUENCES | ROOMLOADER_FLAG.PARTICLES | ROOMLOADER_FLAG.TEXTS | ROOMLOADER_FLAG.BACKGROUNDS | ROOMLOADER_FLAG.EFFECTS,
	ALL = ROOMLOADER_FLAG.CORE | ROOMLOADER_FLAG.EXTENDED,
}
