/// feather ignore all

enum ROOMLOADER_FLAG {
	NONE = 0,
	INSTANCES = 1,
	TILEMAPS = 2,
	SPRITES = 4,
	SEQUENCES = 8,
	TEXTS = 16,
	BACKGROUNDS = 32,
	
	CORE = (ROOMLOADER_FLAG.INSTANCES | ROOMLOADER_FLAG.SPRITES | ROOMLOADER_FLAG.TILEMAPS),
	EXTENDED = (ROOMLOADER_FLAG.SEQUENCES | ROOMLOADER_FLAG.TEXTS | ROOMLOADER_FLAG.BACKGROUNDS),
	ALL = (ROOMLOADER_FLAG.CORE | ROOMLOADER_FLAG.EXTENDED),
}
