/// @feather ignore all

#macro __ROOM_LOADER_LAYER_PREFIX "__room_loader__"

enum ROOM_LOADER_FLAG {
	NONE = 0,
	INSTANCES = 1,
	SPRITES = 2,
	TILEMAPS = 4,
	ALL = (ROOM_LOADER_FLAG.INSTANCES | ROOM_LOADER_FLAG.SPRITES | ROOM_LOADER_FLAG.TILEMAPS),
}
enum ROOM_LOADER_ORIGIN {
	TOP_LEFT, TOP_CENTER, TOP_RIGHT,
	MIDDLE_LEFT, MIDDLE_CENTER, MIDDLE_RIGHT,
	BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT,
}
