/// @feather ignore all

enum ROOMLOADER_FLAG {
	NONE = 0,
	INSTANCES = 1,
	TILEMAPS = 2,
	SPRITES = 4,
	PARTICLE_SYSTEMS = 8,
	SEQUENCES = 16,
	TEXTS = 32,
	BACKGROUNDS = 64,
	
	CORE = (ROOMLOADER_FLAG.INSTANCES | ROOMLOADER_FLAG.SPRITES | ROOMLOADER_FLAG.TILEMAPS),
	EXTENDED = (ROOMLOADER_FLAG.PARTICLE_SYSTEMS | ROOMLOADER_FLAG.SEQUENCES | ROOMLOADER_FLAG.TEXTS | ROOMLOADER_FLAG.BACKGROUNDS),
	ALL = (ROOMLOADER_FLAG.CORE | ROOMLOADER_FLAG.EXTENDED),
}
