/// @feather ignore all

enum ROOM_LOADER_FLAG {
	NONE = 0,
	INSTANCES = 1,
	SPRITES = 2,
	TILEMAPS = 4,
	PARTICLE_SYSTEMS = 8,
	SEQUENCES = 16,
	BACKGROUNDS = 32,
	
	CORE = (ROOM_LOADER_FLAG.INSTANCES | ROOM_LOADER_FLAG.SPRITES | ROOM_LOADER_FLAG.TILEMAPS),
	EXTENDED = (ROOM_LOADER_FLAG.PARTICLE_SYSTEMS | ROOM_LOADER_FLAG.SEQUENCES | ROOM_LOADER_FLAG.BACKGROUNDS),
	ALL = (ROOM_LOADER_FLAG.CORE | ROOM_LOADER_FLAG.EXTENDED),
}
enum ROOM_LOADER_ORIGIN {
	TOP_LEFT, TOP_CENTER, TOP_RIGHT,
	MIDDLE_LEFT, MIDDLE_CENTER, MIDDLE_RIGHT,
	BOTTOM_LEFT, BOTTOM_CENTER, BOTTOM_RIGHT,
}
