name: Deploy VitePress site to GitHub Pages

on:
  push:
    branches: [ main ] # change if your default branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies inside docs/
      - name: Install dependencies
        run: npm ci
        working-directory: ./docs

      # Build the VitePress site inside docs/
      - name: Build site
        run: npm run docs:build
        working-directory: ./docs

      # Upload build output for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/.vitepress/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
